name: Shopify Lighthouse CI
on: [push]
jobs:
    lhci:
      name: Lighthouse
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Lighthouse
        uses: abdulsuhail/lighthouse-ci-action@main
        with:
          app_id: ${{ secrets.SHOP_APP_ID }}
          app_password: "frawsk"
          store: "webpagetest-app.myshopify.com"
          password:  ${{ secrets.SHOP_PASSWORD }}
          lhci_github_app_token: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
