name: Web Page Test
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: WebPageTest Action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Node Setup
        uses: actions/setup-node@v1

      - name: Install Shopify CLI
        run: gem install shopify-cli

      - name: Run Build
        run: npm run build

      - name: WebPageTest
        uses: abdulsuhail/web-test@master
        with:
          with_ngrok: true
          apiKey: ${{ secrets.WPT_API_KEY }}
          uses: WPO-Foundation/webpagetest-github-action@main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          wptOptions: '/.github/workflows/wpt-options.json'
