name: Web Page Test
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: WebPageTest Action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Node Setup
        uses: actions/setup-node@v1

      - name: Install Project Dependencies
        run: npm install

      - name: Install pm2
        run: npm install pm2@latest -g


      - name: Run Build
        run: npm run build

      - name: Start App
        run: pm2 start app.js 
        
      - name: Download ngrok
        run: npm install ngrok -g

      - name: Start ngrok in background
        run: source start-ngrok.sh 9000
      
      - name: WebPageTest
        uses: abdulsuhail/web-test@master
        with:
          with_ngrok: true
          apiKey: ${{ secrets.WPT_API_KEY }}
          label: 'GitHub Action Test'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          wptOptions: '/.github/workflows/wpt-options.json'
